function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Gadfly.Geom.render, (Gadfly.Geom.SubplotGrid, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.render, (Gadfly.Plot,))
    precompile(Gadfly.call, (Array{Any, 1}, Type{Gadfly.Theme},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.BoxplotGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.deferred_label_context, (Gadfly.Geom.LabelGeometry, Gadfly.Aesthetics, Gadfly.Theme, Compose.ParentDrawContext,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.HistogramStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.render_colorful_dodged_bar, (Gadfly.Geom.BarGeometry, Gadfly.Theme, Gadfly.Aesthetics, Symbol,))
    precompile(Gadfly.call, (Array{Any, 1}, Type{Gadfly.Data},))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.BoxplotStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.bounding_order_of_magnitude, (Int64,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.LineGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.PolygonGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Guide.render, (Gadfly.Guide.YTicks, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.render_colorful_stacked_bar, (Gadfly.Geom.BarGeometry, Gadfly.Theme, Gadfly.Aesthetics, Symbol,))
    precompile(Gadfly.Guide.render, (Gadfly.Guide.XTicks, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Guide.layout_guides, (Compose.Context, Gadfly.Coord.SubplotGrid, Gadfly.Theme,))
    precompile(Gadfly.Guide.layout_guides, (Compose.Context, Gadfly.Coord.SubplotGrid, Gadfly.Theme, Gadfly.Guide.PositionedGuide, Vararg{Gadfly.Guide.PositionedGuide},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.RectangularBinGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Guide.layout_guides, (Compose.Context, Gadfly.Coord.Cartesian, Gadfly.Theme, Gadfly.Guide.PositionedGuide, Vararg{Gadfly.Guide.PositionedGuide},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.ViolinGeometry},))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.TickStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.BoxplotGeometry,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.SmoothStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.RibbonGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Guide.render_continuous_color_key, (Base.Dict{ColorTypes.Color, Float64}, DataStructures.OrderedDict{ColorTypes.Color, AbstractString}, Function, Compose.Context, Compose.Measure{Compose.MeasureNil, Compose.MeasureNil}, Gadfly.Theme,))
    precompile(Gadfly.assert_aesthetics_defined, (ASCIIString, Gadfly.Aesthetics, Symbol, Vararg{Symbol},))
    precompile(Gadfly.Geom.render_colorless_bar, (Gadfly.Geom.BarGeometry, Gadfly.Theme, Gadfly.Aesthetics, Symbol,))
    precompile(Gadfly.by_xy_group, (Gadfly.Aesthetics, DataArrays.PooledDataArray{Int64, UInt32, 1}, DataArrays.PooledDataArray{Int64, UInt32, 1}, Int64, Int64,))
    precompile(Gadfly.by_xy_group, (Gadfly.Data, DataArrays.PooledDataArray{Int64, UInt32, 1}, DataArrays.PooledDataArray{Int64, UInt32, 1}, Int64, Int64,))
    precompile(Gadfly.by_xy_group, (Gadfly.Aesthetics, Void, DataArrays.PooledDataArray{Int64, UInt32, 1}, Int64, Int64,))
    precompile(Gadfly.by_xy_group, (Gadfly.Data, DataArrays.PooledDataArray{Int64, UInt32, 1}, Void, Int64, Int64,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.SubplotGrid,))
    precompile(Gadfly.by_xy_group, (Gadfly.Data, Void, DataArrays.PooledDataArray{Int64, UInt32, 1}, Int64, Int64,))
    precompile(Gadfly.by_xy_group, (Gadfly.Aesthetics, DataArrays.PooledDataArray{Int64, UInt32, 1}, Void, Int64, Int64,))
    precompile(Gadfly.Guide.render, (Gadfly.Guide.ZoomSlider, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.XErrorBarGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Coord.apply_coordinate, (Gadfly.Coord.Cartesian, Array{Gadfly.Aesthetics, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.ViolinGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.ContourStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.YErrorBarGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Scale.apply_scale, (Gadfly.Scale.ContinuousColorScale, Array{Gadfly.Aesthetics, 1}, Gadfly.Data, Vararg{Gadfly.Data},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.BarGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.StepStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.Histogram2DStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.FunctionStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.BinMeanStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.HexBinStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.DensityStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Scale.apply_scale, (Gadfly.Scale.DiscreteColorScale, Array{Gadfly.Aesthetics, 1}, Gadfly.Data, Vararg{Gadfly.Data},))
    precompile(Gadfly.optimize_ticks, (Array{Any, 1}, Int32, Int32,))
    precompile(Gadfly.Guide.render, (Gadfly.Guide.ColorKey, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.ViolinStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.PointGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Scale.apply_scale, (Gadfly.Scale.ContinuousScale, Array{Gadfly.Aesthetics, 1}, Gadfly.Data, Vararg{Gadfly.Data},))
    precompile(Gadfly.optimize_ticks, (Array{Any, 1}, Float64, Float64,))
    precompile(Gadfly.optimize_ticks, (Array{Any, 1}, Int64, Int64,))
    precompile(Gadfly.optimize_ticks_typed, (Int64, Int64, Bool, Array{Tuple{Float64, Float64}, 1}, Int64, Int64, Int64, Float64, Float64, Float64, Float64, Bool,))
    precompile(Gadfly.Scale.apply_scale, (Gadfly.Scale.DiscreteScale, Array{Gadfly.Aesthetics, 1}, Gadfly.Data, Vararg{Gadfly.Data},))
    precompile(Gadfly.optimize_ticks_typed, (Int32, Int32, Bool, Array{Tuple{Float64, Float64}, 1}, Int64, Int64, Int64, Float64, Float64, Float64, Float64, Bool,))
    precompile(Gadfly.Guide.render, (Gadfly.Guide.YLabel, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.optimize_ticks_typed, (Float64, Float64, Bool, Array{Tuple{Float64, Float64}, 1}, Int64, Int64, Int64, Float64, Float64, Float64, Float64, Bool,))
    precompile(Gadfly.Guide.render, (Gadfly.Guide.Title, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Coord.call, (Array{Any, 1}, Type{Gadfly.Coord.Cartesian}, Array{Symbol, 1}, Array{Symbol, 1},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.HexagonalBinGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.SubplotGrid}, Type{Gadfly.Geom.LineGeometry}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.concretize, (Array{Float64, 1}, Vararg{Array{Float64, 1}},))
    precompile(Gadfly.optimize_ticks, (Array{Any, 1}, Base.Dates.DateTime, Base.Dates.DateTime,))
    precompile(Gadfly.optimize_ticks, (Array{Any, 1}, Base.Dates.Date, Base.Dates.Date,))
    precompile(Gadfly.Geom.histogram, (Array{Any, 1},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Geom.PointGeometry}, Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.LabelGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.call, (Array{Any, 1}, Type{Gadfly.Stat.HistogramStatistic},))
    precompile(Gadfly.Scale.call, (Array{Any, 1}, Type{Gadfly.Scale.ContinuousScale}, Array{Symbol, 1}, Gadfly.Scale.ContinuousScaleTransform,))
    precompile(Gadfly.Stat.xticks, (Array{Any, 1},))
    precompile(Gadfly.Geom.histogram2d, (Array{Any, 1},))
    precompile(Gadfly.Stat.yticks, (Array{Any, 1},))
    precompile(Gadfly.Geom.polygon_points, (Array{Int64, 1}, Array{Int64, 1}, Bool,))
    precompile(Gadfly.Guide.render, (Gadfly.Guide.XLabel, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Guide.render_discrete_color_key, (Array{ColorTypes.Color, 1}, DataStructures.OrderedDict{ColorTypes.Color, AbstractString}, Function, Compose.Context, Compose.Measure{Compose.MeasureNil, Compose.MeasureNil}, Gadfly.Theme,))
    precompile(Gadfly.cat_aes_var!, (DataArrays.PooledDataArray{ASCIIString, UInt32, 1}, DataArrays.PooledDataArray{ASCIIString, UInt32, 1},))
    precompile(Gadfly.Stat.minimum_span, (Array{Symbol, 1}, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.call, (Array{Any, 1}, Type{Gadfly.Stat.Histogram2DStatistic},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.VLineGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.HLineGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.mean_by_group, (Array{Float64, 1}, Array{Float64, 1}, Array{Float64, 1},))
    precompile(Gadfly.cat_aes_var!, (DataArrays.PooledDataArray{UTF8String, UInt32, 1}, DataArrays.PooledDataArray{UTF8String, UInt32, 1},))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.PolygonGeometry},))
    precompile(Gadfly.Coord.first_concrete_aesthetic_value, (Array{Gadfly.Aesthetics, 1}, Array{Symbol, 1},))
    precompile(Gadfly.Guide.call, (Array{Any, 1}, Type{Gadfly.Guide.YTicks},))
    precompile(Gadfly.Guide.call, (Array{Any, 1}, Type{Gadfly.Guide.XTicks},))
    precompile(Gadfly.Stat.choose_bin_count_1d_discrete, (Array{Int32, 1}, Array{Int32, 1}, Int64, Int64,))
    precompile(Gadfly.cleanmapping, (Array{Any, 1},))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.SubplotGrid}, Function,))
    precompile(Gadfly.Stat.choose_bin_count_1d_discrete, (Array{Float64, 1}, Array{Float64, 1}, Int64, Int64,))
    precompile(Gadfly.assert_aesthetics_undefined, (ASCIIString, Gadfly.Aesthetics, Symbol, Vararg{Symbol},))
    precompile(Gadfly.Scale.call, (Array{Any, 1}, Type{Gadfly.Scale.DiscreteScale}, Array{Symbol, 1},))
    precompile(Gadfly.cleanmapping, (Base.Dict{Symbol, Any},))
    precompile(Gadfly.Stat.mean_by_group, (Array{Int64, 1}, Array{Int64, 1}, Array{Float64, 1},))
    precompile(Gadfly.Scale.call, (Array{Any, 1}, Type{Gadfly.Scale.DiscreteColorScale}, Function,))
    precompile(Gadfly.concat, (Gadfly.Aesthetics, Vararg{Gadfly.Aesthetics},))
    precompile(Gadfly.cat_aes_var!, (DataArrays.PooledDataArray{ColorTypes.RGB{Float32}, UInt32, 1}, DataArrays.PooledDataArray{ColorTypes.RGB{Float32}, UInt32, 1},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.PolygonGeometry,))
    precompile(Gadfly.cat_aes_var!, (DataArrays.PooledDataArray{Int64, UInt32, 1}, DataArrays.PooledDataArray{Int64, UInt32, 1},))
    precompile(Gadfly.Stat.choose_bin_count_2d, (DataArrays.DataArray{Float64, 1}, DataArrays.DataArray{Float64, 1}, Int64, Int64, Int64, Int64,))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.SubplotGrid}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.call, (Type{Gadfly.Aesthetics}, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.choose_bin_count_2d, (Array{Int32, 1}, DataArrays.PooledDataArray{Int64, UInt32, 1}, Int64, Int64, Int64, Int64,))
    precompile(Gadfly.Geom.smooth, (Array{Any, 1},))
    precompile(Gadfly.Guide.render_colorkey_title, (ASCIIString, Gadfly.Theme,))
    precompile(Gadfly.cat_aes_var!, (Array{Int64, 1}, Array{Float64, 1},))
    precompile(Gadfly.Stat.apply_statistic_typed, (Int64, Int64, Array{Any, 1}, Array{Void, 1}, Array{Void, 1},))
    precompile(Gadfly.Coord.call, (Type{Gadfly.Coord.Cartesian}, Array{Symbol, 1}, Array{Symbol, 1},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.ViolinGeometry,))
    precompile(Gadfly.Stat.call, (Array{Any, 1}, Type{Gadfly.Stat.SmoothStatistic},))
    precompile(Gadfly.Scale.call, (Array{Any, 1}, Type{Gadfly.Scale.ContinuousColorScale}, Function,))
    precompile(Gadfly.Stat.call, (Array{Any, 1}, Type{Gadfly.Stat.JitterStatistic}, Array{Symbol, 1},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.LabelGeometry,))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.LabelGeometry},))
    precompile(Gadfly.Scale.color_continuous_gradient, (Array{Any, 1},))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.BarGeometry}, Gadfly.Stat.Identity,))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.BarGeometry}, Gadfly.Stat.HistogramStatistic,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.RibbonGeometry,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.ErrorBarGeometry,))
    precompile(Gadfly.assert_aesthetics_equal_length, (ASCIIString, Gadfly.Aesthetics, Symbol, Vararg{Symbol},))
    precompile(Gadfly.Stat.apply_statistic_typed, (Int64, Int64, DataArrays.PooledDataArray{Int64, UInt32, 1}, Array{Void, 1}, Array{Void, 1},))
    precompile(Gadfly.Stat.choose_bin_count_1d, (DataArrays.DataArray{Float64, 1}, Int64, Int64,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.HLineGeometry,))
    precompile(Gadfly.concrete_maximum, (DataArrays.PooledDataArray{Int64, UInt32, 1},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.VLineGeometry,))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.LineGeometry}, Gadfly.Stat.ContourStatistic,))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.LineGeometry}, Gadfly.Stat.Identity,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.HexagonalBinGeometry,))
    precompile(Gadfly.Stat.choose_bin_count_1d, (Array{Int32, 1}, Int64, Int64,))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.LineGeometry}, Gadfly.Stat.SmoothStatistic,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.RectangularBinGeometry,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.BarGeometry,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.Stat.call, (Array{Any, 1}, Type{Gadfly.Stat.ContourStatistic},))
    precompile(Gadfly.Geom.add_subplot_element, (Gadfly.Geom.SubplotGrid, Gadfly.Geom.BarGeometry,))
    precompile(Gadfly.Scale.apply_scales, (Array{Gadfly.ScaleElement, 1}, Array{Gadfly.Aesthetics, 1}, Gadfly.Data, Vararg{Gadfly.Data},))
    precompile(Gadfly.Geom.add_subplot_element, (Gadfly.Geom.SubplotGrid, Gadfly.Geom.PointGeometry,))
    precompile(Gadfly.Geom.add_subplot_element, (Gadfly.Geom.SubplotGrid, Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.Scale.apply_scales, (Iterators.Distinct{Base.ValueIterator{Base.Dict{Symbol, Gadfly.ScaleElement}}}, Array{Gadfly.Aesthetics, 1}, Gadfly.Data, Vararg{Gadfly.Data},))
    precompile(Gadfly.render_prepared, (Array{Any, 1}, Gadfly.Plot, Gadfly.Coord.Cartesian, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.StatisticElement, 1}, Array{Array{Gadfly.Aesthetics, 1}, 1}, Array{Array{Gadfly.Data, 1}, 1}, Base.Dict{Symbol, Gadfly.ScaleElement}, Array{Gadfly.GuideElement, 1},))
    precompile(Gadfly.concrete_minimum, (Array{Float64, 1},))
    precompile(Gadfly.Stat.call, (Array{Any, 1}, Type{Gadfly.Stat.HexBinStatistic},))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.QQStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.apply_statistic_typed, (Float64, Float64, DataArrays.DataArray{Float64, 1}, Array{Void, 1}, Array{Void, 1},))
    precompile(Gadfly.call, (Type{Gadfly.Aesthetics},))
    precompile(Gadfly.inherit!, (Array{Any, 1}, Gadfly.Aesthetics, Gadfly.Aesthetics,))
    precompile(Gadfly.concrete_minimum, (DataArrays.DataArray{Float64, 1},))
    precompile(Gadfly.Coord.aesthetics_type, (Array{Gadfly.Aesthetics, 1}, Array{Symbol, 1},))
    precompile(Gadfly.concrete_maximum, (DataArrays.DataArray{Float64, 1},))
    precompile(Gadfly.Scale.apply_scale, (Gadfly.Scale.LabelScale, Array{Gadfly.Aesthetics, 1}, Gadfly.Data, Vararg{Gadfly.Data},))
    precompile(Gadfly.concrete_minimum, (DataArrays.PooledDataArray{Int64, UInt32, 1},))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.Stat.call, (Array{Any, 1}, Type{Gadfly.Stat.BinMeanStatistic},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Stat.Identity,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Stat.BinMeanStatistic,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Geom.PointGeometry,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Stat.HistogramStatistic,))
    precompile(Gadfly.call, (Type{Gadfly.Data},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Stat.QQStatistic,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Stat.FunctionStatistic,))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Gadfly.Geom.LabelGeometry,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Stat.JitterStatistic,))
    precompile(Gadfly.Scale.apply_scale_typed!, (DataArrays.DataArray{ColorTypes.RGB{Float32}, 1}, DataArrays.DataArray{Any, 1}, Gadfly.Scale.ContinuousColorScale, Float64, Float64,))
    precompile(Gadfly.Stat.apply_statistic_typed, (Float64, Float64, Array{Int64, 1}, Array{Void, 1}, Array{Void, 1},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.HexagonalBinGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Function, Function, Type{Gadfly.Geom.PointGeometry}, Type{Gadfly.Geom.LabelGeometry},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Stat.StepStatistic,))
    precompile(Gadfly.Scale.apply_scale, (Gadfly.Scale.IdentityScale, Array{Gadfly.Aesthetics, 1}, Gadfly.Data, Vararg{Gadfly.Data},))
    precompile(Gadfly.Stat.choose_bin_count_1d, (DataArrays.PooledDataArray{Int64, UInt32, 1}, Int64, Int64,))
    precompile(Gadfly.concrete_minmax, (Array{Any, 1}, Int64, Int64,))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Stat.FunctionStatistic}, Type{Gadfly.Geom.LineGeometry}, Gadfly.Coord.Cartesian, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel,))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Gadfly.Geom.BarGeometry,))
    precompile(Gadfly.layer, (Array{Any, 1}, Gadfly.Theme, Type{Gadfly.Geom.PointGeometry}, Vararg{Type{Gadfly.Geom.PointGeometry}},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Stat.FunctionStatistic}, Type{Gadfly.Geom.LineGeometry}, Gadfly.Scale.DiscreteColorScale, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Function, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Gadfly.Guide.ColorKey, Gadfly.Coord.Cartesian, Vararg{Gadfly.Coord.Cartesian},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Stat.QQStatistic}, Type{Gadfly.Geom.PointGeometry}, Function,))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Stat.QQStatistic}, Type{Gadfly.Geom.PointGeometry}, Function, Function,))
    precompile(Gadfly.Scale.ln_formatter, (Array{Float64, 1}, Symbol,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Function, Function, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Stat.FunctionStatistic}, Type{Gadfly.Geom.LineGeometry}, Gadfly.Scale.DiscreteColorScale, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Vararg{Gadfly.Guide.YLabel},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Stat.QQStatistic}, Type{Gadfly.Geom.PointGeometry}, Function,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Function, Function, Function,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Stat.FunctionStatistic}, Type{Gadfly.Geom.LineGeometry}, Type{Gadfly.Geom.HLineGeometry}, Type{Gadfly.Geom.VLineGeometry}, Gadfly.Guide.XLabel, Vararg{Union{Union{Gadfly.Theme, DataType, Function, Gadfly.Element}, Array{Gadfly.Layer, 1}}},))
    precompile(Gadfly.layer, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Stat.BinMeanStatistic, Vararg{Union{Gadfly.Theme, DataType, Function, Gadfly.Element}},))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Gadfly.Geom.PointGeometry,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Coord.Cartesian, Function, Function, Function, Type{Gadfly.Geom.RectangularBinGeometry}, Vararg{Union{Union{Gadfly.Theme, DataType, Function, Gadfly.Element}, Array{Gadfly.Layer, 1}}},))
    precompile(Gadfly.layer, (Array{Any, 1}, Type{Gadfly.Geom.PointGeometry}, Gadfly.Theme, Vararg{Gadfly.Theme},))
    precompile(Gadfly.Scale.log10_formatter, (Array{Float64, 1}, Symbol,))
    precompile(Gadfly.layer, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Geom.LineGeometry, Vararg{Gadfly.Geom.LineGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Theme, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Gadfly.Scale.ContinuousScale, Gadfly.Scale.ContinuousScale, Vararg{Union{Union{Gadfly.Theme, DataType, Function, Gadfly.Element}, Array{Gadfly.Layer, 1}}},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Geom.SubplotGrid, Gadfly.Theme,))
    precompile(Gadfly.layer, (Array{Any, 1}, Void, Type{Gadfly.Stat.FunctionStatistic}, Vararg{Union{Gadfly.Theme, DataType, Function, Gadfly.Element}},))
    precompile(Gadfly.layer, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.BarGeometry}, Vararg{Union{Gadfly.Theme, DataType, Function, Gadfly.Element}},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Function, Function,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Stat.FunctionStatistic}, Type{Gadfly.Geom.LineGeometry}, Gadfly.Coord.Cartesian, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Vararg{Gadfly.Guide.YLabel},))
    precompile(Gadfly.Scale.sqrt_formatter, (Array{Float64, 1}, Symbol,))
    precompile(Gadfly.layer, (Array{Any, 1}, Type{Gadfly.Stat.FunctionStatistic}, Type{Gadfly.Geom.LineGeometry}, Vararg{Type{Gadfly.Geom.LineGeometry}},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Theme, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Stat.QQStatistic}, Type{Gadfly.Geom.PointGeometry}, Function, Function,))
    precompile(Gadfly.concrete_minmax, (DataArrays.DataArray{Float64, 1}, Float64, Float64,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Coord.Cartesian, Type{Gadfly.Geom.RectangularBinGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Stat.FunctionStatistic}, Type{Gadfly.Geom.LineGeometry}, Type{Gadfly.Geom.HLineGeometry}, Type{Gadfly.Geom.VLineGeometry}, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Vararg{Gadfly.Guide.YLabel},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.LineGeometry}, Type{Gadfly.Geom.RibbonGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.LineGeometry}, Type{Gadfly.Stat.StepStatistic},))
    precompile(Gadfly.Stat.bin!, (Array{Int64, 1}, DataArrays.DataArray{Float64, 1}, Float64, Float64, Int64,))
    precompile(Gadfly.layer, (Array{Any, 1}, Type{Gadfly.Geom.PointGeometry}, Type{Gadfly.Geom.LabelGeometry}, Vararg{Type{Gadfly.Geom.LabelGeometry}},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Geom.RectangularBinGeometry, Function, Function,))
    precompile(Gadfly.layer, (Array{Any, 1}, Type{Gadfly.Geom.LineGeometry}, Gadfly.Theme, Vararg{Gadfly.Theme},))
    precompile(Gadfly.Stat.call, (Type{Gadfly.Stat.BinMeanStatistic},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Geom.PointGeometry}, Type{Gadfly.Geom.ErrorBarGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Function, Gadfly.Geom.BarGeometry,))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Geom.PointGeometry}, Gadfly.Geom.LabelGeometry,))
    precompile(Gadfly.layer, (Array{Any, 1}, Void, Gadfly.Theme, Vararg{Union{Gadfly.Theme, DataType, Function, Gadfly.Element}},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Array{Gadfly.Layer, 1},))
    precompile(Gadfly.Stat.bin!, (Array{Int64, 1}, DataArrays.PooledDataArray{Int64, UInt32, 1}, Int64, Float64, Int64,))
    precompile(Gadfly.layer, (Array{Any, 1}, Type{Gadfly.Geom.LineGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, Gadfly.Geom.SubplotGrid,))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.BarGeometry},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.LabelGeometry},))
    precompile(Gadfly.layer, (Array{Any, 1}, Void, Type{Gadfly.Geom.PointGeometry}, Vararg{Type{Gadfly.Geom.PointGeometry}},))
    precompile(Gadfly.layer, (Array{Any, 1}, Void, Type{Gadfly.Geom.LineGeometry}, Vararg{Union{Gadfly.Theme, DataType, Function, Gadfly.Element}},))
    precompile(Gadfly.Geom.call, (Array{Any, 1}, Type{Gadfly.Geom.LineGeometry},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.BarGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.PointGeometry}, Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.plot, (Array{Any, 1}, Function,))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Stat.FunctionStatistic}, Type{Gadfly.Geom.LineGeometry}, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel,))
    precompile(Gadfly.Scale.apply_scale_typed!, (DataArrays.DataArray{ColorTypes.RGB{Float32}, 1}, DataArrays.DataArray{Float64, 1}, Gadfly.Scale.ContinuousColorScale, Float64, Float64,))
    precompile(Gadfly.layer, (Array{Any, 1}, Void, Type{Gadfly.Geom.PointGeometry}, Vararg{Union{Gadfly.Theme, DataType, Function, Gadfly.Element}},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.PointGeometry}, Gadfly.Geom.LabelGeometry,))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Int64, 1}, Array{Int64, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.PointGeometry}, Type{Gadfly.Geom.ErrorBarGeometry},))
    precompile(Gadfly.Stat.bincount_pll, (Int64, Int64, Array{Int64, 1}, Float64,))
    precompile(Gadfly.defined_aesthetics, (Gadfly.Aesthetics,))
    precompile(Gadfly.Coord.call, (Array{Any, 1}, Type{Gadfly.Coord.Cartesian},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.Guide.call, (Type{Gadfly.Guide.XTicks},))
    precompile(Gadfly.Stat.apply_statistic_typed, (Float64, Float64, Array{Float64, 1}, Array{Void, 1}, Array{Float64, 1},))
    precompile(Gadfly.Scale.discretize, (Array{ASCIIString, 1}, Void, Void, Bool,))
    precompile(Gadfly.concrete_maximum, (Array{Float64, 1},))
    precompile(Gadfly.Stat.apply_statistic_typed, (Float64, Float64, Array{Float64, 1}, Array{Void, 1}, Array{Void, 1},))
    precompile(Gadfly.Guide.render, (Gadfly.Guide.PanelBackground, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.plot, (Array{Any, 1}, Gadfly.Geom.SubplotGrid, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Gadfly.Guide.Title,))
    precompile(Gadfly.concrete_minimum, (Array{Int32, 1},))
    precompile(Gadfly.concrete_length, (DataArrays.DataArray{Float64, 1},))
    precompile(Gadfly.plot, (Array{Any, 1}, Array{Function, 1}, Int64, Int64,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Geom.SubplotGrid, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Gadfly.Guide.Title,))
    precompile(Gadfly.plot, (Array{Any, 1}, Function, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Gadfly.Guide.ColorKey, Gadfly.Coord.Cartesian,))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Gadfly.Stat.FunctionStatistic,))
    precompile(Gadfly.Scale.make_labeler, (Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Scale.apply_scale_typed!, (DataArrays.DataArray{ColorTypes.RGB{Float32}, 1}, Array{Int64, 1}, Gadfly.Scale.ContinuousColorScale, Float64, Float64,))
    precompile(Gadfly.Stat.apply_statistic_typed, (Int32, Int32, Array{Int32, 1}, Array{Void, 1}, Array{Void, 1},))
    precompile(Gadfly.Geom.default_scales, (Gadfly.Geom.SubplotGrid,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Stat.FunctionStatistic}, Type{Gadfly.Geom.LineGeometry}, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel,))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Int32, 1}, DataArrays.DataArray{Int32, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.plot, (Array{Any, 1}, Gadfly.Scale.ContinuousScale, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.plot, (Array{Any, 1}, Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.Scale.apply_scales, (Iterators.Distinct{Base.ValueIterator{Base.Dict{Symbol, Gadfly.ScaleElement}}}, Gadfly.Data, Gadfly.Data, Vararg{Gadfly.Data},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Stat.HistogramStatistic}, Type{Gadfly.Geom.LineGeometry},))
    precompile(Gadfly.Stat.apply_statistic_typed, (Base.Dates.DateTime, Base.Dates.DateTime, Array{Base.Dates.DateTime, 1}, Array{Void, 1}, Array{Void, 1},))
    precompile(Gadfly.Stat.apply_statistic_typed, (Base.Dates.Date, Base.Dates.Date, Array{Base.Dates.Date, 1}, Array{Void, 1}, Array{Void, 1},))
    precompile(Gadfly.Stat.minvalmaxval, (Base.Dates.Date, Base.Dates.Date, Base.Dates.Date, Void, Void,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Scale.ContinuousScale, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Float64, 1}, Array{Any, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Stat.minvalmaxval, (Base.Dates.DateTime, Base.Dates.DateTime, Base.Dates.DateTime, Void, Void,))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Gadfly.Stat.BinMeanStatistic,))
    precompile(Gadfly.Scale.apply_scale_typed!, (DataArrays.DataArray{ColorTypes.RGB{Float32}, 1}, Array{Float64, 1}, Gadfly.Scale.ContinuousColorScale, Float64, Float64,))
    precompile(Gadfly.plot, (Array{Any, 1}, Function, Function,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Gadfly.Guide.Title,))
    precompile(Gadfly.call, (Type{Gadfly.Plot},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.ViolinGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Gadfly.Guide.Title,))
    precompile(Gadfly.Scale.iscategorical, (Base.Dict{Symbol, Gadfly.ScaleElement}, Symbol,))
    precompile(Gadfly.Stat.minvalmaxval, (Float64, Float64, Float64, Void, Float64,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame,))
    precompile(Gadfly.plot, (Array{Any, 1}, Array{Function, 1}, Int64, Int64, Type{Gadfly.Geom.HLineGeometry}, Type{Gadfly.Geom.VLineGeometry},))
    precompile(Gadfly.bounding_order_of_magnitude, (Int32,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.PointGeometry}, Gadfly.Theme,))
    precompile(Gadfly.plot, (Array{Any, 1}, Function, Int64, Int64, Type{Gadfly.Geom.HLineGeometry}, Type{Gadfly.Geom.VLineGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Stat.BinMeanStatistic}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.BarGeometry}, Type{Gadfly.Geom.ErrorBarGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Function, Type{Gadfly.Geom.BarGeometry},))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Float64, 1}, Array{Float64, 2}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.bounding_order_of_magnitude, (Float64,))
    precompile(Gadfly.Stat.apply_statistic_typed, (Int64, Int64, Array{Int64, 1}, Array{Void, 1}, Array{Void, 1},))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Gadfly.Theme,))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Base.Dates.Date, 1}, DataArrays.DataArray{Base.Dates.Date, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Geom.LineGeometry}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Guide.XTicks, Gadfly.Guide.YTicks,))
    precompile(Gadfly.Stat.minvalmaxval, (Int32, Int32, Int32, Void, Void,))
    precompile(Gadfly.plot, (Array{Any, 1}, Gadfly.Guide.XTicks, Gadfly.Guide.YTicks,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Stat.BinMeanStatistic, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.LineGeometry}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Stat.QQStatistic}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Stat.QQStatistic}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Guide.ColorKey,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.RectangularBinGeometry},))
    precompile(Gadfly.vstack, (Array{Gadfly.Plot, 1},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Function,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.LineGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Geom.BarGeometry,))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Stat.BinMeanStatistic}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, Gadfly.Guide.ColorKey,))
    precompile(Gadfly.layer, (Array{Any, 1}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.concrete_maximum, (Array{Int32, 1},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.BoxplotGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.BarGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Geom.HexagonalBinGeometry},))
    precompile(Gadfly.hstack, (Array{Gadfly.Plot, 1},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Geom.BarGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Type{Gadfly.Geom.HexagonalBinGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Geom.BoxplotGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, Type{Gadfly.Geom.ViolinGeometry},))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Geom.PolygonGeometry,))
    precompile(Gadfly.plot, (Array{Any, 1}, Gadfly.Geom.PolygonGeometry,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Scale.ContinuousColorScale,))
    precompile(Gadfly.plot, (Array{Any, 1}, Gadfly.Scale.ContinuousColorScale,))
    precompile(Gadfly.plot, (Array{Any, 1}, DataFrames.DataFrame, Gadfly.Geom.SubplotGrid,))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Float64, 1}, Array{Float64, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Stat.minvalmaxval, (Float64, Float64, Float64, Void, Void,))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Base.Dates.Date, 1}, Array{Base.Dates.Date, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.LineGeometry}, Gadfly.Stat.Identity,))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.BarGeometry}, Gadfly.Stat.Identity,))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Base.Dates.DateTime, 1}, Array{Base.Dates.DateTime, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Scale.discretize, (DataArrays.PooledDataArray{ASCIIString, UInt8, 1}, Void, Void, Bool,))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.LineGeometry}, Gadfly.Stat.DensityStatistic,))
    precompile(Gadfly.vstack, (Gadfly.Plot, Gadfly.Plot, Gadfly.Plot, Gadfly.Plot, Vararg{Gadfly.Plot},))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Base.Dates.DateTime, 1}, DataArrays.DataArray{Base.Dates.DateTime, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Stat.bin!, (Array{Int64, 1}, Array{Float64, 1}, Float64, Float64, Int64,))
    precompile(Gadfly.concrete_length, (Array{Any, 1},))
    precompile(Gadfly.Stat.call, (Type{Gadfly.Stat.HistogramStatistic},))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Int64, 1}, DataArrays.DataArray{Int64, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.concrete_minmax, (Array{Base.Dates.DateTime, 1}, Base.Dates.DateTime, Base.Dates.DateTime,))
    precompile(Gadfly.concrete_minmax, (Array{Base.Dates.Date, 1}, Base.Dates.Date, Base.Dates.Date,))
    precompile(Gadfly.concrete_minmax, (Array{Int64, 1}, Float64, Float64,))
    precompile(Gadfly.Scale.apply_scales, (Iterators.Distinct{Base.ValueIterator{Base.Dict{Symbol, Gadfly.ScaleElement}}}, Gadfly.Data,))
    precompile(Gadfly.Stat.minvalmaxval, (Int64, Int64, Int64, Void, Void,))
    precompile(Gadfly.plot, (Array{Any, 1},))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Int64, 1}, Base.UnitRange{Int64}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.concrete_minmax, (Array{Int32, 1}, Float64, Float64,))
    precompile(Gadfly.concrete_minmax, (DataArrays.PooledDataArray{Int64, UInt32, 1}, Int64, Int64,))
    precompile(Gadfly.Scale.apply_scale_typed!, (DataArrays.DataArray{Float64, 1}, DataArrays.DataArray{Int64, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Float64, 1}, DataArrays.PooledDataArray{Float64, UInt32, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.concrete_minmax, (Array{Float64, 1}, Float64, Float64,))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.SubplotGrid,))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Float64, 1}, DataArrays.DataArray{Float64, 1}, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.VLineGeometry},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.HLineGeometry},))
    precompile(Gadfly.Scale.apply_scale_typed!, (Array{Float64, 1}, Float64, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Stat.call, (Type{Gadfly.Stat.StepStatistic},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.LineGeometry},))
    precompile(Gadfly.Guide.call, (Type{Gadfly.Guide.YTicks},))
    precompile(Gadfly.hasna, (DataArrays.DataArray{Int32, 1},))
    precompile(Gadfly.Stat.call, (Type{Gadfly.Stat.FunctionStatistic},))
    precompile(Gadfly.classify_data, (Array{Any, 1},))
    precompile(Gadfly.concrete_minmax, (Array{Int32, 1}, Int32, Int32,))
    precompile(Gadfly.Stat.bin!, (Array{Int64, 1}, Array{Int32, 1}, Int32, Float64, Int64,))
    precompile(Gadfly.concrete_minmax, (Array{Int64, 1}, Int64, Int64,))
    precompile(Gadfly.Coord.apply_coordinate, (Gadfly.Coord.SubplotGrid, Array{Gadfly.Aesthetics, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.Stat.apply_statistics, (Array{Gadfly.StatisticElement, 1}, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.SubplotGrid, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.add_subplot_element, (Gadfly.Geom.SubplotGrid, Array{Gadfly.Layer, 1},))
    precompile(Gadfly.Stat.apply_statistics, (Array{Gadfly.StatisticElement, 1}, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.concrete_length, (Iterators.Chain,))
    precompile(Gadfly.Geom.histogram, ())
    precompile(Gadfly.Scale.discretize_make_pda, (Array{Any, 1}, Void,))
    precompile(Gadfly.nonzero_length, (Array{UInt32, 1},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.SubplotGrid}, Type{Gadfly.Geom.BarGeometry},))
    precompile(Gadfly.isallconcrete, (DataArrays.PooledDataArray{Int64, UInt32, 1},))
    precompile(Gadfly.concrete_length, (Array{Int32, 1},))
    precompile(Gadfly.concrete_length, (DataArrays.PooledDataArray{Int64, UInt32, 1},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.SubplotGrid}, Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1},))
    precompile(Gadfly.concrete_minmax, (Array{Function, 1}, Float64, Float64,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.ErrorBarGeometry, Gadfly.Theme, Gadfly.Aesthetics,))
    precompile(Gadfly.nonzero_length, (Array{UInt8, 1},))
    precompile(Gadfly.Scale.discretize, (Array{Int64, 1}, Void, Void, Bool,))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.SubplotGrid}, Function, Type{Gadfly.Geom.LineGeometry},))
    precompile(Gadfly.isallconcrete, (Array{Int64, 1},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.SubplotGrid}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.Scale.discretize, (DataArrays.DataArray{ASCIIString, 1}, Void, Void, Bool,))
    precompile(Gadfly.classify_data, (DataArrays.DataArray{Any, 1},))
    precompile(Gadfly.Geom.histogram2d, ())
    precompile(Gadfly.cat_aes_var!, (Void, DataArrays.DataArray{Float64, 1},))
    precompile(Gadfly.Scale.discretize, (DataArrays.DataArray{Int64, 1}, Void, Void, Bool,))
    precompile(Gadfly.concrete_length, (Array{Int64, 1},))
    precompile(Gadfly.Geom.contour, ())
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.SubplotGrid}, Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1}, Gadfly.Guide.XTicks,))
    precompile(Gadfly.hasna, (DataArrays.DataArray{Base.Dates.DateTime, 1},))
    precompile(Gadfly.isallconcrete, (Array{Float64, 1},))
    precompile(Gadfly.hasna, (DataArrays.DataArray{Float64, 1},))
    precompile(Gadfly.Scale.discretize_make_pda, (Array{Int64, 1}, Array{Int64, 1},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.SubplotGrid}, Type{Gadfly.Geom.LineGeometry}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.hasna, (DataArrays.PooledDataArray{Float64, UInt32, 1},))
    precompile(Gadfly.Scale.discretize, (DataArrays.DataArray{ASCIIString, 1}, Array{ASCIIString, 1}, Void, Bool,))
    precompile(Gadfly.plot, (Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1}, Function,))
    precompile(Gadfly.hasna, (DataArrays.DataArray{Base.Dates.Date, 1},))
    precompile(Gadfly.Scale.discretize, (DataArrays.DataArray{UTF8String, 1}, Void, Void, Bool,))
    precompile(Gadfly.hasna, (DataArrays.DataArray{Int64, 1},))
    precompile(Gadfly.concrete_length, (Array{Float64, 1},))
    precompile(Gadfly.svg_color_class_from_label, (ASCIIString,))
    precompile(Gadfly.Scale.discretize, (DataArrays.DataArray{Int32, 1}, Void, Void, Bool,))
    precompile(Gadfly.spy, (Array{Float64, 2}, Gadfly.Coord.Cartesian, Vararg{Gadfly.Coord.Cartesian},))
    precompile(Gadfly.Scale.discretize_make_pda, (DataArrays.DataArray{ASCIIString, 1}, Void,))
    precompile(Gadfly.concrete_length, (Array{Base.Dates.DateTime, 1},))
    precompile(Gadfly.isallconcrete, (Array{Int32, 1},))
    precompile(Gadfly.isallconcrete, (Array{Base.Dates.DateTime, 1},))
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.SubplotGrid}, Function,))
    precompile(Gadfly.concrete_length, (Array{Base.Dates.Date, 1},))
    precompile(Gadfly.default_middle_color, (ColorTypes.RGB{Float32},))
    precompile(Gadfly.Guide.call, (Type{Gadfly.Guide.PositionedGuide}, Array{Compose.Context, 1}, Int64, Gadfly.Guide.RightGuidePosition,))
    precompile(Gadfly.Scale.discretize_make_pda, (Array{ASCIIString, 1}, Array{ASCIIString, 1},))
    precompile(Gadfly.Scale.discretize_make_pda, (Array{Symbol, 1}, Array{Symbol, 1},))
    precompile(Gadfly.plot, (DataFrames.DataFrame, Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1}, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Gadfly.Guide.Title, Vararg{Gadfly.Guide.Title},))
    precompile(Gadfly.plot, (DataFrames.DataFrame, Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1}, Function, Vararg{Function},))
    precompile(Gadfly.Scale.discretize_make_pda, (Array{Any, 1}, Array{Any, 1},))
    precompile(Gadfly.Scale.discretize_make_pda, (Array{AbstractString, 1}, Array{AbstractString, 1},))
    precompile(Gadfly.optimize_ticks, (Float64, Float64,))
    precompile(Gadfly.Coord.call, (Type{Gadfly.Coord.Cartesian},))
    precompile(Gadfly.layer, (Array{Function, 1}, Int64, Int64,))
    precompile(Gadfly.Scale.discretize_make_pda, (DataArrays.PooledDataArray{ASCIIString, UInt8, 1}, Void,))
    precompile(Gadfly.default_continuous_highlight_color, (ColorTypes.RGB{Float32},))
    precompile(Gadfly.Guide.call, (Type{Gadfly.Guide.XLabel}, ASCIIString,))
    precompile(Gadfly.Scale.discretize_make_pda, (DataArrays.DataArray{UTF8String, 1}, Void,))
    precompile(Gadfly.Scale.discretize_make_pda, (Array{ASCIIString, 1}, Void,))
    precompile(Gadfly.Scale.discretize_make_pda, (Array{Symbol, 1}, Void,))
    precompile(Gadfly.Scale.discretize_make_pda, (Array{AbstractString, 1}, Array{ASCIIString, 1},))
    precompile(Gadfly.Scale.discretize_make_pda, (DataArrays.DataArray{Int32, 1}, Void,))
    precompile(Gadfly.Scale.discretize_make_pda, (Array{Int64, 1}, Void,))
    precompile(Gadfly.Scale.discretize_make_pda, (Array{AbstractString, 1}, Void,))
    precompile(Gadfly.optimize_ticks, (Int64, Int64,))
    precompile(Gadfly.Geom.smooth, ())
    precompile(Gadfly.Scale.x_discrete, ())
    precompile(Gadfly.Scale.discretize_make_pda, (Array{Any, 1}, Array{ASCIIString, 1},))
    precompile(Gadfly.evalmapping, (DataFrames.DataFrame, ASCIIString,))
    precompile(Gadfly.Stat.x_jitter, ())
    precompile(Gadfly.plot, (Gadfly.Geom.SubplotGrid,))
    precompile(Gadfly.cat_aes_var!, (Void, DataArrays.PooledDataArray{ASCIIString, UInt32, 1},))
    precompile(Gadfly.Scale.y_discrete, ())
    precompile(Gadfly.Scale.discretize_make_pda, (DataArrays.DataArray{ASCIIString, 1}, Array{ASCIIString, 1},))
    precompile(Gadfly.cat_aes_var!, (Void, DataArrays.PooledDataArray{Int64, UInt32, 1},))
    precompile(Gadfly.plot, (Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1}, Gadfly.Guide.XLabel, Gadfly.Guide.YLabel, Gadfly.Guide.Title,))
    precompile(Gadfly.Guide.call, (Type{Gadfly.Guide.YLabel}, ASCIIString,))
    precompile(Gadfly.Scale.discretize_make_pda, (DataArrays.DataArray{Int64, 1}, Void,))
    precompile(Gadfly.jsplotdata, (ASCIIString, ASCIIString,))
    precompile(Gadfly.jsdata, (ASCIIString, ASCIIString,))
    precompile(Gadfly.cat_aes_var!, (Void, DataArrays.PooledDataArray{UTF8String, UInt32, 1},))
    precompile(Gadfly.Stat.y_jitter, ())
    precompile(Gadfly.Guide.call, (Type{Gadfly.Guide.ManualColorKey}, ASCIIString, Array{ASCIIString, 1}, Array{ASCIIString, 1},))
    precompile(Gadfly.group_color_isless, (Tuple{Int64, ColorTypes.RGB{Float32}}, Tuple{Int64, ColorTypes.RGB{Float32}},))
    precompile(Gadfly.Scale.discretize_make_pda, (DataArrays.DataArray{Int64, 1}, Array{Int64, 1},))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.BoxplotGeometry,))
    precompile(Gadfly.Scale.color_discrete_manual, (ASCIIString, Vararg{ASCIIString},))
    precompile(Gadfly.Scale.color_discrete_hue, ())
    precompile(Gadfly.Stat.default_scales, (Gadfly.Stat.ContourStatistic,))
    precompile(Gadfly.__init__, ())
    precompile(Gadfly.Geom.add_subplot_element, (Gadfly.Geom.SubplotGrid, Gadfly.Scale.DiscreteColorScale,))
    precompile(Gadfly.Guide.default_statistic, (Gadfly.Guide.YTicks,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Coord.Cartesian,))
    precompile(Gadfly.Stat.default_scales, (Gadfly.Stat.QQStatistic,))
    precompile(Gadfly.plot, (DataFrames.DataFrame, Gadfly.Geom.SubplotGrid,))
    precompile(Gadfly.Geom.path, ())
    precompile(Gadfly.Geom.call, (Type{Gadfly.Geom.RectangularBinGeometry}, Gadfly.Stat.Histogram2DStatistic,))
    precompile(Gadfly.default_stroke_color, (ColorTypes.RGB{Float32},))
    precompile(Gadfly.cat_aes_var!, (Void, Array{Float64, 2},))
    precompile(Gadfly.Scale.discretize_make_pda, (DataArrays.DataArray{Int32, 1}, Array{Int32, 1},))
    precompile(Gadfly.Scale.discretize_make_pda, (DataArrays.DataArray{UTF8String, 1}, Array{UTF8String, 1},))
    precompile(Gadfly.layer, (Void, Type{Gadfly.Geom.PointGeometry}, Gadfly.Theme,))
    precompile(Gadfly.layer, (Void, Function, Gadfly.Theme,))
    precompile(Gadfly.plot, (DataFrames.DataFrame, Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1},))
    precompile(Gadfly.plot, (Array{Function, 1}, Int64, Int64, Gadfly.Scale.DiscreteColorScale,))
    precompile(Gadfly.default_lowlight_color, (ColorTypes.RGB{Float32},))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.ErrorBarGeometry,))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Type{Gadfly.Stat.FunctionStatistic},))
    precompile(Gadfly.plot, (Array{Function, 1}, Int64, Int64, Gadfly.Coord.Cartesian,))
    precompile(Gadfly.plot, (Function, Int64, Int64, Gadfly.Coord.Cartesian,))
    precompile(Gadfly.undefined_aesthetics, (Gadfly.Aesthetics, Symbol, Vararg{Symbol},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Theme,))
    precompile(Gadfly.Guide.default_statistic, (Gadfly.Guide.XTicks,))
    precompile(Gadfly.default_scales, (Gadfly.Geom.HexagonalBinGeometry,))
    precompile(Gadfly.cat_aes_var!, (Void, Array{Int32, 1},))
    precompile(Gadfly.default_discrete_highlight_color, (ColorTypes.RGB{Float32},))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.BarGeometry,))
    precompile(Gadfly.draw, (Compose.SVG, Gadfly.Plot,))
    precompile(Gadfly.layer, (Type{Gadfly.Geom.PointGeometry}, Gadfly.Theme,))
    precompile(Gadfly.layer, (Function, Gadfly.Theme,))
    precompile(Gadfly.cat_aes_var!, (Void, DataArrays.DataArray{ColorTypes.RGB{Float32}, 1},))
    #precompile(Gadfly.draw, (Compose.Image{Compose.PNGBackend}, Gadfly.Plot,))
    precompile(Gadfly.plot, (Array{Gadfly.Layer, 1}, Array{Gadfly.Layer, 1},))
    precompile(Gadfly.Geom.add_subplot_element, (Gadfly.Geom.SubplotGrid, Type{Gadfly.Geom.LineGeometry},))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.PolygonGeometry,))
    precompile(Gadfly.layer, (DataFrames.DataFrame, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Type{Gadfly.Geom.BarGeometry},))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.RectangularBinGeometry,))
    precompile(Gadfly.Stat.default_scales, (Gadfly.Stat.HistogramStatistic,))
    precompile(Gadfly.color_isless, (ColorTypes.RGB{Float32}, ColorTypes.RGB{Float32},))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.FunctionStatistic,))
    precompile(Gadfly.issomething, (Array{Float64, 1},))
    precompile(Gadfly.lerp, (Float64, Float64, Float64,))
    precompile(Gadfly.Coord.call, (Type{Gadfly.Coord.SubplotGrid},))
    precompile(Gadfly.cat_aes_var!, (Void, DataArrays.PooledDataArray{ColorTypes.RGB{Float32}, UInt32, 1},))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.PointGeometry,))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.ViolinGeometry,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.ViolinGeometry,))
    precompile(Gadfly.cat_aes_var!, (Void, Array{Int64, 1},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Guide.XTicks,))
    precompile(Gadfly.draw, (Compose.PGF, Gadfly.Plot,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Function,))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Type{Gadfly.Geom.LabelGeometry},))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.DensityStatistic,))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Type{Gadfly.Geom.LineGeometry},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Array{Gadfly.Layer, 1},))
    precompile(Gadfly.default_scales, (Gadfly.Geom.PolygonGeometry,))
    precompile(Gadfly.Stat.default_scales, (Gadfly.Stat.DensityStatistic,))
    precompile(Gadfly.cat_aes_var!, (Function, Function,))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.HexagonalBinGeometry,))
    precompile(Gadfly.Scale.discretize, (DataArrays.PooledDataArray{ASCIIString, UInt8, 1}, Array{ASCIIString, 1}, Void, Bool,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Guide.XLabel,))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.JitterStatistic, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.ContourStatistic,))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.BinMeanStatistic,))
    precompile(Gadfly.default_scales, (Gadfly.Geom.ViolinGeometry,))
    precompile(Gadfly.default_scales, (Gadfly.Stat.BinMeanStatistic,))
    precompile(Gadfly.Scale.discretize, (Array{ASCIIString, 1}, Array{ASCIIString, 1}, Void, Bool,))
    precompile(Gadfly.Scale.element_aesthetics, (Gadfly.Scale.IdentityScale,))
    precompile(Gadfly.default_scales, (Gadfly.Stat.ViolinStatistic,))
    precompile(Gadfly.inherit!, (Gadfly.Aesthetics, Gadfly.Aesthetics,))
    precompile(Gadfly.Stat.default_scales, (Gadfly.Stat.HexBinStatistic,))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.QQStatistic,))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.Histogram2DStatistic,))
    precompile(Gadfly.plot, (Function, Float64, Int64, Float64, Int64,))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Function,))
    precompile(Gadfly.Scale.discretize, (Array{Any, 1}, Array{ASCIIString, 1}, Void, Bool,))
    precompile(Gadfly.Scale.discretize, (Array{Symbol, 1}, Array{Symbol, 1}, Void, Bool,))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.LabelGeometry,))
    precompile(Gadfly.cat_aes_var!, (Void, Array{Any, 1},))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.SmoothStatistic,))
    precompile(Gadfly.Scale.discretize, (Array{AbstractString, 1}, Array{ASCIIString, 1}, Void, Bool,))
    precompile(Gadfly.issomething, (Void,))
    precompile(Gadfly.isconcrete, (Int32,))
    precompile(Gadfly.Geom.add_subplot_element, (Gadfly.Geom.SubplotGrid, Function,))
    precompile(Gadfly.escape_id, (ASCIIString,))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.ViolinStatistic,))
    precompile(Gadfly.default_scales, (Gadfly.Geom.BoxplotGeometry,))
    precompile(Gadfly.Guide.call, (Type{Gadfly.Guide.ColorKey}, ASCIIString,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.PolygonGeometry,))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.default_scales, (Gadfly.Stat.BoxplotStatistic,))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.RibbonGeometry,))
    precompile(Gadfly.default_scales, (Gadfly.Geom.ErrorBarGeometry,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.PointGeometry,))
    precompile(Gadfly.cat_aes_var!, (Void, Array{ColorTypes.RGB{Float32}, 1},))
    precompile(Gadfly.cat_aes_var!, (ASCIIString, Void,))
    #precompile(Gadfly.element_aesthetics, (Gadfly.Stat.HexBinStatistic,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Geom.RectangularBinGeometry},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.LineGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.default_discrete_highlight_color, (ColorTypes.RGBA{Float32},))
    precompile(Gadfly.cat_aes_var!, (Void, Bool,))
    precompile(Gadfly.Guide.call, (Type{Gadfly.Guide.Title}, ASCIIString,))
    precompile(Gadfly.isconcrete, (Float64,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.RectangularBinGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.Geom.density, ())
    precompile(Gadfly.default_scales, (Gadfly.Stat.Identity,))
    precompile(Gadfly.default_scales, (Gadfly.Geom.PointGeometry,))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.BoxplotStatistic,))
    precompile(Gadfly.plot, (Array{Function, 1}, Int64, Int64,))
    precompile(Gadfly.inherit, (Gadfly.Aesthetics, Gadfly.Aesthetics,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Geom.RibbonGeometry},))
    precompile(Gadfly.element_aesthetics, (Function,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Guide.ColorKey,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Scale.ContinuousColorScale,))
    #precompile(Gadfly.element_aesthetics, (Gadfly.Stat.Identity,))
    precompile(Gadfly.default_scales, (Gadfly.Geom.LabelGeometry,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Guide.YTicks,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.ViolinGeometry,))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.StepStatistic,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.BarGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Stat.HistogramStatistic},))
    precompile(Gadfly.copy, (Gadfly.Aesthetics,))
    precompile(Gadfly.Scale.element_aesthetics, (Gadfly.Scale.LabelScale,))
    precompile(Gadfly.add_plot_element!, (Array{Gadfly.Layer, 1}, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.default_statistic, (Gadfly.Guide.ZoomSlider,))
    precompile(Gadfly.default_scales, (Gadfly.Geom.HLineGeometry,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.BoxplotGeometry,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Geom.HLineGeometry},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Geom.LabelGeometry},))
    precompile(Gadfly.default_scales, (Gadfly.Stat.SmoothStatistic,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Geom.BarGeometry},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Stat.StepStatistic},))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.HLineGeometry,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.RibbonGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.multilevel_ticks, (Int64, Int64,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.VLineGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Scale.DiscreteScale,))
    precompile(Gadfly.Scale.discretize_make_pda, (DataArrays.PooledDataArray{ASCIIString, UInt8, 1}, Array{ASCIIString, 1},))
    precompile(Gadfly.default_scales, (Gadfly.Stat.JitterStatistic,))
    precompile(Gadfly.multilevel_ticks, (Base.Dates.DateTime, Base.Dates.DateTime,))
    precompile(Gadfly.cat_aes_var!, (Void, DataStructures.OrderedDict{Any, Any},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.HLineGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.default_scales, (Gadfly.Geom.RectangularBinGeometry,))
    precompile(Gadfly.Geom.add_subplot_element, (Gadfly.Geom.SubplotGrid, Gadfly.Guide.XTicks,))
    precompile(Gadfly.multilevel_ticks, (Float64, Float64,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.HexagonalBinGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Stat.BinMeanStatistic},))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.PolygonGeometry,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Geom.VLineGeometry},))
    precompile(Gadfly.default_scales, (Gadfly.Stat.StepStatistic,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Geom.LineGeometry},))
    precompile(Gadfly.default_scales, (Gadfly.Geom.VLineGeometry,))
    precompile(Gadfly.default_scales, (Gadfly.Geom.RibbonGeometry,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Stat.FunctionStatistic},))
    precompile(Gadfly.default_scales, (Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.HLineGeometry,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Guide.YLabel,))
    precompile(Gadfly.default_statistic, (Gadfly.Guide.ColorKey,))
    precompile(Gadfly.issomething, (Array{Base.Dates.DateTime, 1},))
    precompile(Gadfly.Scale.identity_formatter, (Array{Float64, 1}, Symbol,))
    precompile(Gadfly.default_scales, (Gadfly.Geom.BarGeometry,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.BoxplotGeometry,))
    precompile(Gadfly.issomething, (Array{Int64, 1},))
    precompile(Gadfly.default_statistic, (Gadfly.Guide.Title,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.LabelGeometry,))
    precompile(Gadfly.default_statistic, (Gadfly.Guide.PanelBackground,))
    precompile(Gadfly.Scale.element_aesthetics, (Gadfly.Scale.ContinuousColorScale,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.ErrorBarGeometry,))
    precompile(Gadfly.default_statistic, (Gadfly.Guide.XLabel,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.LabelGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.Stat.default_scales, (Gadfly.Stat.FunctionStatistic,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Scale.DiscreteColorScale,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.Scale.identity_formatter, (Array{Base.Dates.DateTime, 1},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Gadfly.Guide.Title,))
    precompile(Gadfly.hasna, (Array{Float64, 2},))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.PointGeometry,))
    precompile(Gadfly.Scale.sqrt_formatter, (Array{Float64, 1},))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.Identity, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.Cartesian, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.ErrorBarGeometry,))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.HistogramStatistic,))
    precompile(Gadfly.Scale.log10_formatter, (Array{Float64, 1},))
    precompile(Gadfly.Stat.apply_statistic, (Gadfly.Stat.Identity, Base.Dict{Symbol, Gadfly.ScaleElement}, Gadfly.Coord.SubplotGrid, Gadfly.Aesthetics,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.SubplotGrid,))
    precompile(Gadfly.Scale.ln_formatter, (Array{Float64, 1},))
    precompile(Gadfly.Scale.identity_formatter, (Array{Int64, 1}, Symbol,))
    precompile(Gadfly.isconcrete, (Base.Dates.DateTime,))
    precompile(Gadfly.Scale.element_aesthetics, (Gadfly.Scale.DiscreteColorScale,))
    precompile(Gadfly.cat_aes_var!, (Void, Base.Dict{ColorTypes.Color, Float64},))
    precompile(Gadfly.cat_aes_var!, (Array{Int32, 1}, Array{Int32, 1},))
    precompile(Gadfly.cat_aes_var!, (ASCIIString, ASCIIString,))
    precompile(Gadfly.cat_aes_var!, (Array{Bool, 1}, Array{Bool, 1},))
    precompile(Gadfly.cat_aes_var!, (Array{Float64, 1}, Array{Float64, 1},))
    precompile(Gadfly.cat_aes_var!, (Array{Int64, 1}, Array{Int64, 1},))
    precompile(Gadfly.default_statistic, (Gadfly.Guide.YLabel,))
    precompile(Gadfly.isconcrete, (Base.Dates.Date,))
    precompile(Gadfly.Geom.element_aesthetics, (Gadfly.Geom.VLineGeometry,))
    precompile(Gadfly.isconcrete, (Int64,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.HLineGeometry,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.VLineGeometry,))
    precompile(Gadfly.cat_aes_var!, (Base.Dict{Symbol, AbstractString}, Base.Dict{Symbol, AbstractString},))
    precompile(Gadfly.Scale.identity_formatter, (Array{Float64, 1},))
    precompile(Gadfly.cat_aes_var!, (Void, Base.Dict{Symbol, AbstractString},))
    precompile(Gadfly.Stat.default_scales, (Gadfly.Stat.Histogram2DStatistic,))
    precompile(Gadfly.classify_data, (DataArrays.DataArray{Int32, 1},))
    precompile(Gadfly.Geom.layers, (Gadfly.Geom.SubplotGrid,))
    precompile(Gadfly.classify_data, (DataArrays.PooledDataArray{ASCIIString, UInt8, 1},))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.LabelGeometry,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.HexagonalBinGeometry,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.RectangularBinGeometry,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.RibbonGeometry,))
    precompile(Gadfly.cat_aes_var!, (DataArrays.PooledDataArray{Int64, UInt32, 1}, Void,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.BarGeometry,))
    precompile(Gadfly.cat_aes_var!, (DataStructures.OrderedDict{Any, Any}, DataStructures.OrderedDict{Any, Any},))
    precompile(Gadfly.isconcrete, (DataArrays.NAtype,))
    precompile(Gadfly.hasna, (Float64,))
    precompile(Gadfly.cat_aes_var!, (Void, Array{Base.Dates.Date, 1},))
    precompile(Gadfly.cat_aes_var!, (Void, Array{Base.Dates.DateTime, 1},))
    precompile(Gadfly.cat_aes_var!, (Void, Array{Bool, 1},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.PolygonGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.cat_aes_var!, (Void, Array{Float64, 1},))
    precompile(Gadfly.cat_aes_var!, (Void, ASCIIString,))
    precompile(Gadfly.Scale.color_continuous_gradient, ())
    precompile(Gadfly.cat_aes_var!, (Void, Array{Array{Float64, 1}, 1},))
    precompile(Gadfly.classify_data, (Base.UnitRange{Int64},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.hasna, (Base.UnitRange{Int64},))
    precompile(Gadfly.hasna, (Array{Base.Dates.Date, 1},))
    precompile(Gadfly.cat_aes_var!, (Array{Float64, 1}, Void,))
    precompile(Gadfly.hasna, (Array{Float64, 1},))
    precompile(Gadfly.cat_aes_var!, (Void, Void,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.BoxplotGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.cat_aes_var!, (Void, Function,))
    precompile(Gadfly.hasna, (Array{Any, 1},))
    precompile(Gadfly.hasna, (Array{Base.Dates.DateTime, 1},))
    precompile(Gadfly.hasna, (Array{Int64, 1},))
    precompile(Gadfly.render_prepared, (Gadfly.Plot, Gadfly.Coord.Cartesian, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.StatisticElement, 1}, Array{Array{Gadfly.Aesthetics, 1}, 1}, Array{Array{Gadfly.Data, 1}, 1}, Base.Dict{Symbol, Gadfly.ScaleElement}, Array{Gadfly.GuideElement, 1},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.ViolinGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.classify_data, (Array{Float64, 2},))
    precompile(Gadfly.Geom.element_coordinate_type, (Gadfly.Geom.SubplotGrid,))
    precompile(Gadfly.Scale.element_aesthetics, (Gadfly.Scale.ContinuousScale,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.LineGeometry,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.BarGeometry,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.RectangularBinGeometry,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.HexagonalBinGeometry,))
    precompile(Gadfly.Geom.default_statistic, (Gadfly.Geom.RibbonGeometry,))
    precompile(Gadfly.render_prepared, (Gadfly.Plot, Gadfly.Coord.SubplotGrid, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.StatisticElement, 1}, Array{Array{Gadfly.Aesthetics, 1}, 1}, Array{Array{Gadfly.Data, 1}, 1}, Base.Dict{Symbol, Gadfly.ScaleElement}, Array{Gadfly.GuideElement, 1},))
    #precompile(Gadfly.Stat.element_aesthetics, (Gadfly.Stat.JitterStatistic,))
    precompile(Gadfly.element_coordinate_type, (Gadfly.Geom.VLineGeometry,))
    precompile(Gadfly.Scale.element_aesthetics, (Gadfly.Scale.DiscreteScale,))
    precompile(Gadfly.classify_data, (DataArrays.DataArray{Float64, 1},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Geom.ErrorBarGeometry},))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.PointGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.classify_data, (DataArrays.PooledDataArray{Float64, UInt32, 1},))
    precompile(Gadfly.classify_data, (DataArrays.DataArray{Base.Dates.DateTime, 1},))
    precompile(Gadfly.classify_data, (DataArrays.DataArray{Int64, 1},))
    precompile(Gadfly.classify_data, (Array{Base.Dates.Date, 1},))
    precompile(Gadfly.classify_data, (Array{ASCIIString, 1},))
    precompile(Gadfly.classify_data, (Array{Float64, 1},))
    precompile(Gadfly.Geom.add_subplot_element, (Gadfly.Geom.SubplotGrid, Type{Gadfly.Geom.PointGeometry},))
    precompile(Gadfly.classify_data, (DataArrays.DataArray{ASCIIString, 1},))
    precompile(Gadfly.classify_data, (DataArrays.DataArray{Base.Dates.Date, 1},))
    precompile(Gadfly.classify_data, (DataArrays.DataArray{UTF8String, 1},))
    precompile(Gadfly.classify_data, (Array{Base.Dates.DateTime, 1},))
    precompile(Gadfly.Scale.discretize, (Array{ASCIIString, 1}, Void, Void,))
    precompile(Gadfly.classify_data, (Array{Symbol, 1},))
    precompile(Gadfly.cat_aes_var!, (Array{Float64, 1}, Array{Function, 1},))
    precompile(Gadfly.Scale.discretize, (DataArrays.PooledDataArray{ASCIIString, UInt8, 1}, Void, Void,))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Stat.Identity},))
    precompile(Gadfly.classify_data, (Array{Int64, 1},))
    precompile(Gadfly.Scale.discretize, (DataArrays.DataArray{Int32, 1}, Void, Void,))
    precompile(Gadfly.Geom.render, (Gadfly.Geom.ErrorBarGeometry, Gadfly.Theme, Gadfly.Aesthetics, Array{Gadfly.Aesthetics, 1}, Array{Gadfly.Data, 1}, Base.Dict{Symbol, Gadfly.ScaleElement},))
    precompile(Gadfly.add_plot_element!, (Gadfly.Plot, DataFrames.DataFrame, Type{Gadfly.Stat.QQStatistic},))
    precompile(Gadfly.Scale.discretize, (Array{Int64, 1}, Void, Void,))
    precompile(Gadfly.Scale.discretize, (DataArrays.DataArray{ASCIIString, 1}, Void, Void,))
    precompile(Gadfly.Scale.discretize, (DataArrays.DataArray{Int64, 1}, Void, Void,))
end
