name: TagBot
on:
  schedule:
    - cron: 0 0 * * 0
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.TAGBOT_PAT }}
          lookback: 7
